name: Validate JSON

on:
  push:
  pull_request:

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Validate JSON files
        run: python .github/scripts/validate-json.py